const START_NOTIFICATION_SERVICE = 'PUSH_RECEIVER:::START_NOTIFICATION_SERVICE';
const NOTIFICATION_SERVICE_STARTED =
  'PUSH_RECEIVER:::NOTIFICATION_SERVICE_STARTED';
const NOTIFICATION_SERVICE_ERROR = 'PUSH_RECEIVER:::NOTIFICATION_SERVICE_ERROR';
const NOTIFICATION_RECEIVED = 'PUSH_RECEIVER:::NOTIFICATION_RECEIVED';
const CRASH_APP = 'PUSH_RECEIVER:::CRASH_APP';
const CHANGE_COMPANY = 'PUSH_RECEIVER:::CHANGE_COMPANY';
const GET_REMEMBER_ME = 'GET:::REMEMBER_ME';
const SAVE_REMEMBER_ME = 'SAVE:::REMEMBER_ME';
const DELETE_REMEMBER_ME = 'DELETE:::REMEMBER_ME';
const STORE_REMEMBER = 'storeRemember';
const ENV_REMEMBER = 'envRemember';
const APP_LOGOUT = 'APP:::LOGOUT';
const COUNT_UNREAD_MESSAGE = 'COUNT:::UNREAD_MESSAGE';
const GET_CURRENT_APP_VERSION = 'APP::GET_CURRENT_APP_VERSION';

module.exports = {
  START_NOTIFICATION_SERVICE,
  NOTIFICATION_SERVICE_STARTED,
  NOTIFICATION_SERVICE_ERROR,
  NOTIFICATION_RECEIVED,
  CRASH_APP,
  CHANGE_COMPANY,
  GET_REMEMBER_ME,
  SAVE_REMEMBER_ME,
  DELETE_REMEMBER_ME,
  STORE_REMEMBER,
  ENV_REMEMBER,
  APP_LOGOUT,
  COUNT_UNREAD_MESSAGE,
  GET_CURRENT_APP_VERSION
};
