export const DynamicParameter = new Map<string, string>([
  ['user_first_name', null],
  ['user_fullname', null],
  ['user_full_name', null],
  ['user_role', null],
  ['supplier_name', null],
  ['short_property_address', null],
  ['full_property_address', null],
  ['property_region', null],
  ['$maintenance_expenditure_limit', null],
  ['key_number', null],
  ['key_description', null],
  ['next_inspection_date', null],
  ['next_inspection_start_time', null],
  ['next_inspection_end_time', null],
  ['company_name', null],
  ['company_address', null],
  ['company_phone_number', null],
  ['company_link', null],
  ['company_working_hours', null],
  ['company_account_name', null],
  ['company_BSB', null],
  ['company_account_number', null],
  ['PM_name', null],
  ['sender_name', null],
  ['sender_role', null],
  ['tenancy_name', null],
  ['tenant_name', null],
  ['tenancy_id', null],
  ['tenant_id', null],
  ['lease_start', null],
  ['lease_end', null],
  ['$rent_amount', null],
  ['$bond_amount_required', null],
  ['$next_rent_amount', null],
  ['tenant_next_rent_review', null],
  ['$effective_rent_arrears_amount', null],
  ['day_rent_in_arrears', null],
  ['effective_rent_paid_to_date', null],
  ['moving_out_date', null],
  ['$total_outstanding_invoices', null],
  ['lease_period', null],
  ['period_type', null],
  ['landlord_name', null],
  ['breach_reason', null],
  ['remedy_date', null],
  ['entry_reason', null],
  ['entry_time', null],
  ['entry_date', null],
  ['form_name', null],
  ['schedule_date', null],
  ['schedule_time', null],
  ['event_name', null],
  ['event_date', null],
  ['event_time', null],
  ['file_name', null],
  ['contact_name', null],
  ['contact_address', null],
  ['contact_email_address', null],
  ['contact_phone_number', null],
  ['contact_information', null],
  ['calendar_event_name', null],
  ['calendar_event_date', null],
  ['calendar_event_time', null],
  ['vacate_type', null],
  ['notice_date', null],
  ['vacate_date', null],
  ['termination_date', null],
  ['charge_to_date', null],
  ['vacate_description', null],
  ['leasing_tenancy_name', null],
  ['leasing_original_lease_start', null],
  ['leasing_lease_start', null],
  ['leasing_lease_end', null],
  ['leasing_lease_period', null],
  ['leasing_period_type', null],
  ['$leasing_rent_amount', null],
  ['leasing_payment_period', null],
  ['rent_start_date', null],
  ['rent_description', null],
  ['next_rent_review', null],
  ['bond_account_name', null],
  ['bond_required_name', null],
  ['$bond_amount_lodged_direct', null],
  ['pt_lease_start', null],
  ['pt_lease_end', null],
  ['$rent_change_amount', null],
  ['lease_period_type', null],
  ['rent_change_effective_date', null],
  ['signed_lease_document_name', null],
  ['note_description', null],
  ['routine_inspection_date', null],
  ['routine_inspection_start_time', null],
  ['routine_inspection_end_time', null],
  ['routine_tenant_notes', null],
  ['routine_tenant_actions', null],
  ['routine_landlord_notes', null],
  ['routine_follow_up_items', null],
  ['reschedule_inspection_link', null],
  ['ingoing_inspection_date', null],
  ['ingoing_inspection_start_time', null],
  ['ingoing_inspection_end_time', null],
  ['ingoing_tenant_notes', null],
  ['ingoing_tenant_actions', null],
  ['ingoing_landlord_notes', null],
  ['ingoing_follow_up_items', null],
  ['outgoing_inspection_date', null],
  ['outgoing_inspection_start_time', null],
  ['outgoing_inspection_end_time', null],
  ['outgoing_tenant_notes', null],
  ['outgoing_tenant_actions', null],
  ['outgoing_landlord_notes', null],
  ['outgoing_follow_up_items', null],
  ['compliance_category', null],
  ['service_reason', null],
  ['compliance_lease_start', null],
  ['compliance_lease_end', null],
  ['expiry_date', null],
  ['next_service_date', null],
  ['maintenance_summary', null],
  ['request_summary', null],
  ['creditor_name', null],
  ['creditor_invoice_description', null],
  ['$creditor_invoice_amount', null],
  ['creditor_due_date', null],
  ['creditor_invoice_status', null],
  ['creditor_invoice_reference', null],
  ['linked_tenancy_invoice_description', null],
  ['$linked_tenancy_invoice_amount', null],
  ['linked_tenancy_due_date', null],
  ['linked_tenancy_invoice_status', null],
  ['linked_tenancy_name_invoice', null],
  ['account_name', null],
  ['tenancy_name_invoice', null],
  ['tenancy_invoice_description', null],
  ['$tenancy_invoice_amount', null],
  ['tenancy_due_date', null],
  ['tenancy_invoice_status', null],
  ['maintenance_creditor_name', null],
  ['maintenance_invoice_description', null],
  ['$maintenance_invoice_amount', null],
  ['maintenance_due_date', null],
  ['maintenance_invoice_reference', null],
  ['lease_duration', null],
  ['rent_period', null],
  ['$bond_amount', null],
  ['$bond_increase_paid', null],
  ['condition', null],
  ['$pet_bond_amount', null],
  ['vacate_tenant_name', null],
  ['vacate_tenancy_name', null],
  ['$rent_owing', null],
  ['$outstanding_invoices_fees', null],
  ['tenant_notes', null],
  ['tenant_actions', null],
  ['owner_notes', null],
  ['follow_up_items', null],
  ['inspection_form_name', null],
  ['inspection_local_file_name', null],
  ['inspection_rei_form_name', null],
  ['$bond_amount_returned', null],
  ['$bond_amount_deducted', null],
  ['reason_bond_deduction', null],
  ['$break_lease_fee', null],
  ['$advertising_fees', null],
  ['other_fees_name', null],
  ['$other_fees_amount', null],
  ['break_lease_form_name', null],
  ['break_lease_local_file_name', null],
  ['break_lease_rei_form_name', null],
  ['letting_type', null],
  ['letting_period_type', null],
  ['$recommended_rental_amount', null],
  ['payment_period', null],
  ['recommended_lease_duration', null],
  ['application_name_1', null],
  ['application_summary_1', null],
  ['application_name_2', null],
  ['application_summary_2', null],
  ['application_name_3', null],
  ['application_summary_3', null],
  ['$bond_amount_due', null],
  ['bond_form_name', null],
  ['bond_local_file_name', null],
  ['bond_rei_form_name', null],
  ['report_deadline', null],
  ['report_form_name', null],
  ['report_local_file_name', null],
  ['report_rei_form_name', null],
  ['custom_event_name', null],
  ['custom_event_date', null],
  ['custom_event_time', null],
  ['authority_start_date', null],
  ['authority_end_date', null]
]);

export enum DynamicParameterType {
  TENANCY = 'tenancy',
  PT_TENANCY_INVOICE = 'ptTenancyInvoice',
  PT_CREDITOR_INVOICE = 'ptCreditorInvoice',
  PT_NOTE = 'ptNote',
  PT_MAINTENANCE_INVOICE = 'ptMaintenanceInvoice',
  RM_ISSUES = 'rmIssues',
  RM_NOTES = 'rmNotes',
  PT_ROUTINE_INSPECTION = 'ptRoutineInspection',
  PT_INGOING_INSPECTION = 'ptIngoingInspection',
  PT_OUTGOING_INSPECTION = 'ptOutgoingInspection',
  PT_COMPLIANCE = 'ptCompliance',
  CALENDAR_EVENT_BREACH_REMEDY_DATE = 'calendarEventBreachRemedy',
  CALENDAR_EVENT_ENTRY_NOTICE = 'calendarEventEntry',
  RM_INSPECTION = 'rmInspections',
  CALENDAR_EVENT_CUSTOM = 'calendarEventCustom',
  RM_NEW_TENANT = 'rmNewTenant',
  REQUEST_SUMMARY = 'requestSummary'
}

export const DynamicParameterGroups = new Map<string, string[]>([
  [
    DynamicParameterType.TENANCY,
    [
      'tenancy_name',
      'tenancy_id',
      'lease_start',
      'lease_end',
      '$rent_amount',
      '$effective_rent_arrears_amount',
      'lease_period',
      'rent_period',
      'due_day',
      'tenant_charge',
      'period_type',
      'tenant_name',
      'tenant_id',
      'tenant_next_rent_review'
    ]
  ],
  [DynamicParameterType.REQUEST_SUMMARY, ['request_summary']],
  [DynamicParameterType.PT_NOTE, ['note_description']],
  [
    DynamicParameterType.PT_CREDITOR_INVOICE,
    [
      'creditor_name',
      'creditor_invoice_description',
      '$creditor_invoice_amount',
      'creditor_due_date',
      'creditor_invoice_status',
      'creditor_invoice_reference',
      'linked_tenancy_invoice_description',
      '$linked_tenancy_invoice_amount',
      'linked_tenancy_due_date',
      'linked_tenancy_invoice_status',
      'linked_tenancy_name_invoice'
    ]
  ],
  [
    DynamicParameterType.PT_TENANCY_INVOICE,
    [
      'tenancy_invoice_description',
      '$tenancy_invoice_amount',
      'tenancy_due_date',
      'tenancy_invoice_status',
      'tenancy_name_invoice',
      'account_name'
    ]
  ],
  [
    DynamicParameterType.PT_MAINTENANCE_INVOICE,
    [
      'maintenance_invoice_description',
      '$maintenance_invoice_amount',
      'maintenance_due_date',
      'maintenance_creditor_name',
      'maintenance_invoice_reference'
    ]
  ],
  [
    DynamicParameterType.PT_ROUTINE_INSPECTION,
    [
      'routine_inspection_date',
      'routine_inspection_start_time',
      'routine_inspection_end_time',
      'routine_tenant_notes',
      'routine_tenant_actions',
      'routine_landlord_notes',
      'routine_follow_up_items',
      'reschedule_inspection_link'
    ]
  ],
  [
    DynamicParameterType.PT_INGOING_INSPECTION,
    [
      'ingoing_inspection_date',
      'ingoing_inspection_start_time',
      'ingoing_inspection_end_time',
      'ingoing_tenant_notes',
      'ingoing_tenant_actions',
      'ingoing_landlord_notes',
      'ingoing_follow_up_items'
    ]
  ],
  [
    DynamicParameterType.PT_OUTGOING_INSPECTION,
    [
      'outgoing_inspection_date',
      'outgoing_inspection_start_time',
      'outgoing_inspection_end_time',
      'outgoing_tenant_notes',
      'outgoing_tenant_actions',
      'outgoing_landlord_notes',
      'outgoing_follow_up_items'
    ]
  ],
  [
    DynamicParameterType.PT_COMPLIANCE,
    [
      'compliance_item',
      'item_managed_by',
      'item_service_by',
      'authority_form_received_state',
      'expiry_date',
      'last_service_date',
      'next_service_date'
    ]
  ],
  // [
  //   DynamicParameterType.RM_ISSUES,
  //   [
  //     'issue_title',
  //     'issue_schedule_date',
  //     'issue_due_date',
  //     'issue_open_date',
  //     'issue_open_time',
  //     'issue_close_date',
  //     'issue_close_time',
  //     'issue_status',
  //     'issue_category',
  //     'issue_priority',
  //     'issue_project',
  //     'issue_vendor',
  //     'issue_job',
  //     'issue_description',
  //     'issue_resolution',
  //     'inventory_item',
  //     'checklist_description',
  //     'issue_note_description'
  //   ]
  // ],
  // [DynamicParameterType.RM_NOTES, ['note_description']],
  [
    DynamicParameterType.CALENDAR_EVENT_CUSTOM,
    ['custom_event_name', 'custom_event_date', 'custom_event_time']
  ],
  [
    DynamicParameterType.CALENDAR_EVENT_BREACH_REMEDY_DATE,
    ['breach_reason', 'remedy_date']
  ],
  [
    DynamicParameterType.CALENDAR_EVENT_ENTRY_NOTICE,
    ['entry_reason', 'entry_time', 'entry_date']
  ]
  // [
  //   DynamicParameterType.RM_INSPECTION,
  //   [
  //     'inspection_tenant',
  //     'inspection_status',
  //     'inspection_type',
  //     'inspection_date',
  //     'scheduled_inspection_date',
  //     'inspection_description',
  //     'inspection_notes',
  //     'inspection_area',
  //     'inspection_item',
  //     'inspection_item_details'
  //   ]
  // ],
  // [
  //   DynamicParameterType.RM_NEW_TENANT,
  //   [
  //     'new_tenant_first_name',
  //     'new_tenant_last_name',
  //     'new_tenant_address',
  //     'tenant_move_in_date',
  //     'tenant_move_out_date',
  //     'tenant_notice_date',
  //     'tenant_expected_move_out',
  //     'tenant_lease_start',
  //     'tenant_lease_end',
  //     'tenant_lease_sign',
  //     'tenant_lease_term',
  //     'tenant_contact_name',
  //     'deposit_type',
  //     'deposit_amount',
  //     'deposit_date',
  //     'tenant_rent_period',
  //     'tenant_due_day',
  //     'tax_type_ID',
  //     'tenant_subsidies',
  //     'property_charge_of_new_tenant',
  //     'unit_charge_of_new_tenant',
  //     'unit_type_charge_of_new_tenant',
  //     'tenant_charge_of_new_tenant',
  //     'one_time_charges',
  //     'user_defined_fields'
  //   ]
  // ]
]);

export enum EFallback {
  UNKNOWN = 'unknown',
  NOT_APPLICABLE = 'N/A',
  UNAVAILABLE = 'unavailable',
  MAINTENANCE_EXPENDITURE_LIMIT = 'the agreed maintenance expenditure limit',
  CONDITIONS_COPY = 'no conditions',
  DOCUMENT = 'document'
}

export const DynamicParameterFallBack = {
  key_number: EFallback.UNAVAILABLE,
  key_description: EFallback.UNAVAILABLE,
  $bond_amount_required: EFallback.UNAVAILABLE,
  $next_rent_amount: EFallback.UNAVAILABLE,
  tenant_next_rent_review: EFallback.UNAVAILABLE,
  $effective_rent_arrears_amount: EFallback.UNAVAILABLE,
  day_rent_in_arrears: EFallback.UNAVAILABLE,
  effective_rent_paid_to_date: EFallback.UNAVAILABLE,
  moving_out_date: EFallback.UNAVAILABLE,
  $total_outstanding_invoices: EFallback.UNAVAILABLE,
  next_inspection_date: EFallback.UNAVAILABLE,
  next_inspection_start_time: EFallback.UNAVAILABLE,
  next_inspection_end_time: EFallback.UNAVAILABLE,
  $maintenance_expenditure_limit: EFallback.MAINTENANCE_EXPENDITURE_LIMIT,
  conditions_copy: EFallback.CONDITIONS_COPY,
  authority_start_date: EFallback.UNAVAILABLE,
  authority_end_date: EFallback.UNAVAILABLE
};
