export enum TaskStatusType {
  assigned = 'ASSIGNED',
  unassigned = 'UNASSIGNED',
  inprogress = 'INPROGRESS',
  completed = 'COMPLETED',
  resolved = 'RESOLVED',
  deleted = 'DELETED',
  mailfolder = 'MAILFOLDER',
  inprogressspace = 'IN PROGRESS',
  my_task = 'MY_TASK',
  my_task_space = 'MY TASKS',
  team_task = 'TEAM_TASK',
  team_task_space = 'TEAM TASKS',
  team_messages = 'TEAM_MESSAGES',
  my_messages = 'MY_MESSAGES',
  moved = 'MOVED',
  spam = 'SPAM',
  cancelled = 'CANCELLED',
  open = 'OPEN',
  deleteTaskSpam = 'DELETE_TASK_SPAM',
  deleteTaskSpamOutlook = 'DELETE_TASK_SPAM_OUTLOOK',
  draft = 'DRAFT',
  reopen = 'REOPEN'
}
