export enum EEventType {
  ARREAR = 'ARREAR',
  VACATE = 'VACATE',
  BREACH_REMEDY = 'BREACH_REMEDY',
  LEASE_END = 'LEASE_END',
  LEASE_START = 'LEASE_START',
  GENERAL_EXPIRY = 'GENERAL_EXPIRY',
  ROUTINE_INSPECTION = 'ROUTINE_INSPECTION',
  SMOKE_ALARM_EXPIRY = 'SMOKE_ALARM_EXPIRY',
  INGOING_INSPECTION = 'INGOING_INSPECTION',
  OUTGOING_INSPECTION = 'OUTGOING_INSPECTION',
  GENERAL_NEXT_SERVICE = 'GENERAL_NEXT_SERVICE',
  SMOKE_ALARM_NEXT_SERVICE = 'SMOKE_ALARM_NEXT_SERVICE',
  ENTRY_NOTICE = 'ENTRY_NOTICE',
  ISSUE = 'ISSUE',
  MOVE_IN_DATE = 'MOVE_IN',
  MOVE_OUT_DATE = 'MOVE_OUT',
  TENANT_INVOICE_DUE_DATE = 'INVOICE',
  CUSTOM_EVENT = 'CUSTOM_EVENT',
  COMPLIANCE_NEXT_SERVICE = 'COMPLIANCE_NEXT_SERVICE',
  COMPLIANCE_EXPIRY = 'COMPLIANCE_EXPIRY',
  ALL_EVENT = 'ALL_EVENT',
  AUTHORITY_START = 'AUTHORITY_START',
  AUTHORITY_END = 'AUTHORITY_END',
  NEXT_RENT_REVIEW = 'NEXT_RENT_REVIEW'
}
export enum EEventStatus {
  OPENED = 'OPENED',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED',
  ACTIVE = 'ACTIVE'
}

export enum ECurrentTab {
  LINKED_TASKS = 'LINKED TASKS',
  HISTORICAL_EVENTS = 'HISTORICAL EVENTS'
}

export enum EHistoricalEventStatus {
  CANCELLED = 'Cancelled',
  CANCEL = 'Cancel',
  SCHEDULED = 'Scheduled',
  RESCHEDULED = 'Rescheduled',
  CLOSED = 'Closed'
}

export enum EReminderType {
  LEASE_RENEWAL = 'LEASE_RENEWAL',
  ROUTINE_INSPECTION = 'ROUTINE_INSPECTION',
  SMOKE_ALARM = 'SMOKE_ALARM',
  GENERAL_COMPLIANCE = 'GENERAL_COMPLIANCE',
  TENANT_VACATE = 'TENANT_VACATE',
  INGOING_INSPECTION = 'INGOING_INSPECTION',
  LEASE_START = 'LEASE_START',
  OUTGOING_INSPECTION = 'OUTGOING_INSPECTION',
  ARREAR = 'ARREAR',
  BREACH_REMEDY_DATE = 'BREACH_REMEDY_DATE',
  ENTRY_NOTICE_DATE = 'ENTRY_NOTICE_DATE'
}

export enum ERepeatType {
  ANNUALLY = 'ANNUALLY',
  ONCE = 'ONCE',
  MONTHLY = 'MONTHLY'
}
