export enum ContactType {
  ADVERTISING_SITES = 'ADVERTISING_SITES',
  BANKS = 'BANKS',
  BODY_CORPORATES = 'BODY_CORPORATES',
  COURTS = 'COURTS',
  NEIGHBOURS = 'NEIGHBOURS',
  SOFTWARE_COMPANY = 'SOFTWARE_COMPANY',
  INSURANCE_COMPANY = 'INSURANCE_COMPANY',
  DOCUSIGN = 'DOCUSIGN',
  OTHER = 'OTHER'
}

export enum EConfirmContactType {
  LANDLORD = 'LANDLORD',
  TENANT = 'TENANT',
  SUPPLIER = 'SUPPLIER',
  OTHER = 'OTHER',
  AGENT = 'AGENT',
  EXTERNAL = 'EXTERNAL',
  TENANT_UNIT = 'TENANT_UNIT',
  TENANT_PROPERTY = 'TENANT_PROPERTY',
  TENANT_PROSPECT = 'TENANT_PROSPECT',
  LANDLORD_PROSPECT = 'LANDLORD_PROSPECT',
  OWNER = 'OWNER',
  OWNER_PROSPECT = 'OWNER_PROSPECT',
  UNIDENTIFIED = 'UNIDENTIFIED',
  MAILBOX = 'MAILBOX',
  LEAD = 'LEAD'
}
