export enum DynamicType {
  CALENDER_EVENT = 'CALENDER_EVENT',
  COMMUNICATION_STEP = 'COMMUNICATION_STEP',
  PT_COMPONENT = 'PT_COMPONENT'
}
export enum PTComponentType {
  VACATE = 'VACATE',
  LEASING = 'LEASING',
  LEASEENEWAL = 'LEASEENEWAL',
  NOTE = 'NOTE',
  ROUTINE_INSPECTION = 'ROUTINE_INSPECTION',
  INGOING_INSPECTION = 'INGOING_INSPECTION',
  OUTGOING_INSPECTION = 'OUTGOING_INSPECTION',
  COMPLIANCE_SMOKE_ALARM = 'COMPLIANCE_SMOKE_ALARM',
  MAINTANENCE = 'MAINTANENCE',
  TENANCY_INVOICE = 'TENANCY_INVOICE',
  MAINTANENCE_INVOICE = 'MAINTANENCE_INVOICE',
  CREDITOR_INVOICE = 'CREDITOR_INVOICE'
}
export enum CommunicationStepType {
  SEND_BASIC_EMAIL = 'send_basic_email',
  SEND_ATTACHMENT = 'send_attachment',
  SCHEDULE_REMINDER = 'schedule_reminder',
  SEND_CONVERSATION_FILES = 'send_conversation_files',
  SEND_CONTACT_CARD = 'send_contact_card',
  SEND_CALENDAR_EVENT = 'send_calendar_event',
  SEND_REQUEST = 'send_request'
}
