export enum EKeyFilterContact {
  CRM = 'CRM',
  PORTFOLIO = 'PORTFOLIO',
  ROLES = 'ROLES',
  PROPERTY_STATUS = 'PROPERTY_STATUS',
  STATUS = 'STATUS',
  LAST_IMPORT = 'LAST_IMPORT',
  AGENCIES = 'AGENCIES'
}
