export enum NotificationStatusEnum {
  SEEN = 'SEEN',
  UN_SEEN = 'UNSEEN'
}

export enum NotificationTypeEnum {
  NEW_TASK = 'NEW_TASK',
  NEW_TASK_UNIDENTIFIED = 'NEW_TASK_UNIDENTIFIED',
  NEW_TASK_NO_PORTFOLIO = 'NEW_TASK_NO_PORTFOLIO',
  NEW_MESSAGE = 'NEW_MESSAGE',
  ASSIGNED_TASK = 'ASSIGNED_TASK',
  UNASSIGNED_TASK = 'UNASSIGNED_TASK',
  RECEIVED_REPLY = 'RECEIVED_REPLY',
  CALL_TRANSCRIPTION = 'CALL_TRANSCRIPTION',
  CANCELLED_TASK = 'CANCELLED_TASK',
  RESCHEDULED_TASK = 'RESCHEDULED_TASK',
  COMPLETED_TASK = 'COMPLETED_TASK',
  REMINDER = 'REMINDER',
  RESCHEDULE_REQUEST = 'RESCHEDULE_REQUEST',
  EVENT_CHANGE_DATA = 'EVENT_CHANGE_DATA',
  NEW_SHARED_MAIL_BOX = 'NEW_SHARED_MAIL_BOX',
  NEW_INTERNAL_NOTE_MENTIONED = 'NEW_INTERNAL_NOTE_MENTIONED',
  NEW_INTERNAL_NOTE_COMMENTED = 'NEW_INTERNAL_NOTE_COMMENTED',
  COMPANY_POLICY = 'COMPANY_POLICY'
}

export enum EventChangeStatusEnum {
  INSPECTION_CHANGE_TIME = 'INSPECTION_CHANGE_TIME',
  INSPECTION_CHANGE_STATUS = 'INSPECTION_CHANGE_STATUS',
  LEASE_CHANGE_TIME_START = 'LEASE_CHANGE_TIME_START',
  LEASE_CHANGE_TIME_END = 'LEASE_CHANGE_TIME_END',
  INVOICE_CHANGE_STATUS = 'INVOICE_CHANGE_STATUS',
  COMPLIANCE_CHANGE_EXPIRY_DATE = 'COMPLIANCE_CHANGE_EXPIRY_DATE',
  COMPLIANCE_CHANGE_NEXT_SERVICE_DATE = 'COMPLIANCE_CHANGE_NEXT_SERVICE_DATE',
  COMPLIANCE_CANCEL_EXPIRY_DATE = 'COMPLIANCE_CANCEL_EXPIRY_DATE',
  COMPLIANCE_CANCEL_NEXT_SERVICE_DATE = 'COMPLIANCE_CANCEL_NEXT_SERVICE_DATE',
  COMPLIANCE_CHANGE_STATUS_EXPIRY_DATE = 'COMPLIANCE_CHANGE_STATUS_EXPIRY_DATE',
  COMPLIANCE_CHANGE_STATUS_NEXT_SERVICE_DATE = 'COMPLIANCE_CHANGE_STATUS_NEXT_SERVICE_DATE',
  COMPLIANCE_DELETE_EXPIRY_DATE = 'COMPLIANCE_DELETE_EXPIRY_DATE',
  COMPLIANCE_DELETE_NEXT_SERVICE_DATE = 'COMPLIANCE_DELETE_NEXT_SERVICE_DATE',
  VACATE_CHANGE_TIME = 'VACATE_CHANGE_TIME',
  ARREAR_INVOICE_CHANGE = 'ARREAR_INVOICE_CHANGE',
  ARREAR_RENT_CHANGE = 'ARREAR_RENT_CHANGE',
  BREACH_REMEDY_DATE_CHANGE = 'BREACH_REMEDY_DATE_CHANGE',
  LEASE_END_CHANGE_TIME_RM = 'LEASE_END_CHANGE_TIME_RM',
  LEASE_START_CHANGE_TIME_RM = 'LEASE_START_CHANGE_TIME_RM',
  MOVE_IN_CHANGE_TIME_RM = 'MOVE_IN_CHANGE_TIME_RM',
  MOVE_OUT_CHANGE_TIME_RM = 'MOVE_OUT_CHANGE_TIME_RM',
  INSPECTION_CHANGE_TIME_RM = 'INSPECTION_CHANGE_TIME_RM',
  INSPECTION_CHANGE_STATUS_RM = 'INSPECTION_CHANGE_STATUS_RM',
  ISSUE_OPEN_CHANGE_TIME_RM = 'ISSUE_OPEN_CHANGE_TIME_RM',
  ISSUE_OPEN_CHANGE_STATUS_RM = 'ISSUE_OPEN_CHANGE_STATUS_RM',
  INVOICE_CHANGE_STATUS_RM = 'INVOICE_CHANGE_STATUS_RM'
}

export enum NotificationTabEnum {
  UNREAD,
  ALL
}
