export enum AppVersionEvent {
  VERSION_DETECTED = 'VERSION_DETECTED',
  VERSION_READY = 'VERSION_READY',
  VERSION_INSTALLATION_FAILED = 'VERSION_INSTALLATION_FAILED',
  NO_NEW_VERSION_DETECTED = 'NO_NEW_VERSION_DETECTED'
}
