export enum EPopupType {
  isTrudiSendMessage = 'isTrudiSendMessage',
  isSelectFiles = 'isSelectFiles',
  isPopupAmount = 'isPopupAmount',
  isPopupRequireAmount = 'isPopupRequireAmount',
  isPopupBreakLease = 'isPopupBreakLease',
  attachEntryNote = 'attachEntryNote',
  uploadAttachments = 'uploadAttachments',
  selectREIDocument = 'selectREIDocument',
  reviewREIDocument = 'reviewREIDocument',
  attachDraftForm = 'attachDraftForm',
  isShowLeaveNoticeDetail = 'isShowLeaveNoticeDetail',
  isShowInspectionNotesOrActionItems = 'isShowInspectionNotesOrActionItems',
  createTask = 'createTask',
  sendContactCard = 'sendContactCard',
  bondLodgement = 'bondLodgement',
  returnFormDate = 'returnFormDate',
  isPopupConditions = 'isPopupConditions',
  isPopupCaptureLease = 'isPopupCaptureLease',
  isShowApplicationShortList = 'isShowApplicationShortList',
  isInspectionAction = 'isInspectionAction',
  selectEvent = 'selectEvent',
  bondSummaryPopup = 'bondSummaryPopup',
  prescreen = 'prescreen',
  lettingRecommendation = 'lettingRecommendation',
  eventSelect = 'eventSelect',
  confirmEssential = 'confirmEssential',
  sendMsg = 'sendMsg'
}

export enum EActionType {
  UPDATE_PT = 'UPDATE_PT',
  UPDATE_DECISION = 'UPDATE_DECISION',
  SET_NULL = 'SET_NULL',
  INIT = 'INIT',
  UPDATE_TRUDI_BUTTON = 'UPDATE_TRUDI_BUTTON',
  ESSENTIAL_CONFIRM = 'ESSENTIAL_CONFIRM',
  ESSENTIAL_RESET = 'ESSENTIAL_RESET',
  ESSENTIAL_SET_BACK = 'ESSENTIAL_SET_BACK',
  UPDATE_RM = 'UPDATE_RM'
}
