const START_NOTIFICATION_SERVICE = 'PUSH_RECEIVER:::START_NOTIFICATION_SERVICE';
const NOTIFICATION_SERVICE_STARTED =
  'PUSH_RECEIVER:::NOTIFICATION_SERVICE_STARTED';
const NOTIFICATION_SERVICE_ERROR = 'PUSH_RECEIVER:::NOTIFICATION_SERVICE_ERROR';
const NOTIFICATION_RECEIVED = 'PUSH_RECEIVER:::NOTIFICATION_RECEIVED';
const CRASH_APP = 'PUSH_RECEIVER:::CRASH_APP';
const CHANGE_COMPANY = 'PUSH_RECEIVER:::CHANGE_COMPANY';
const REFRESH_APP_LATER = 'REFESH_APP:::REFRESH_LATER';
const SHOW_REFRESH_POPUP = 'REFESH_APP:::SHOW_REFRESH_POPUP';
const REFRESH_APP = 'REFESH_APP:::REFRESH_APP';
const REDIRECT_PREPROD = 'REDIRECT:::REDIRECT_PREPROD';
const APP_LOGOUT = 'APP:::LOGOUT';
const GET_REMEMBER_ME = 'GET:::REMEMBER_ME';
const SAVE_REMEMBER_ME = 'SAVE:::REMEMBER_ME';
const DELETE_REMEMBER_ME = 'DELETE:::REMEMBER_ME';
const COUNT_UNREAD_MESSAGE = 'COUNT:::UNREAD_MESSAGE';
const SHOW_UPDATE_VERSION_APP = 'SHOW_UPDATE_VERSION_APP';
const GET_CURRENT_APP_VERSION = 'APP::GET_CURRENT_APP_VERSION';

module.exports = {
  START_NOTIFICATION_SERVICE,
  NOTIFICATION_SERVICE_STARTED,
  NOTIFICATION_SERVICE_ERROR,
  NOTIFICATION_RECEIVED,
  CRASH_APP,
  CHANGE_COMPANY,
  REFRESH_APP_LATER,
  SHOW_REFRESH_POPUP,
  REFRESH_APP,
  REDIRECT_PREPROD,
  APP_LOGOUT,
  GET_REMEMBER_ME,
  SAVE_REMEMBER_ME,
  DELETE_REMEMBER_ME,
  COUNT_UNREAD_MESSAGE,
  SHOW_UPDATE_VERSION_APP,
  GET_CURRENT_APP_VERSION
};
