export enum EPropertyProfileTab {
  DETAILS = 'DETAILS',
  NOTES = 'NOTES',
  EVENTS = 'EVENTS'
}
export enum EPropertyProfileStep {
  PROPERTY_DETAIL = 'PROPERTY_DETAIL',
  TENANCY_DETAIL = 'TENANCY_DETAIL',
  TENANT_DETAIL = 'TENANT_DETAIL',
  OWNERSHIP_DETAIL = 'OWNERSHIP_DETAIL',
  EVENT_DETAIL = 'EVENT_DETAIL',
  PARENT_PROPERTY_DETAIL = 'PARENT_PROPERTY_DETAIL'
}
export enum EFilterTabEventButton {
  UPCOMING_EVENTS = 'UPCOMING_EVENTS',
  PREVIOUS_EVENTS = 'PREVIOUS_EVENTS'
}

export enum EPreviewUserType {
  LANDLORD = 'LANDLORD',
  TENANT = 'TENANT'
}

export enum ELinkTaskStatus {
  INPROGRESS = 'INPROGRESS',
  COMPLETED = 'COMPLETED'
}

export enum EPropertyProfileTabIndex {
  DETAILS = 0,
  NOTES = 1,
  EVENTS = 2
}
